"""add series table

Revision ID: 2679fcd9900f
Revises: 5a4e053551d1
Create Date: 2026-04-19 17:14:57.908540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2679fcd9900f'
down_revision = '5a4e053551d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('series',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    if_not_exists=True
                    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_books_series_id', 'series', ['series_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_series_id', type_='foreignkey')
        batch_op.drop_column('series_id')

    op.drop_table('series')
    # ### end Alembic commands ###
