"""add project table

Revision ID: 98cc45eb1df4
Revises: 2679fcd9900f
Create Date: 2026-04-19 17:44:01.386030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cc45eb1df4'
down_revision = '2679fcd9900f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('about_series')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_series', sa.VARCHAR(), nullable=True))

    op.drop_table('projects')
    # ### end Alembic commands ###
